import sys
import os
import subprocess

def get_prop_names(properties_gen):
    names = []
    with open(properties_gen, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if ':' not in line:
                continue
            names.append(line.split(':')[0].strip())
    return names

def main():
    if len(sys.argv) < 2:
        print("Usage: gen_props.py <gen_parser_path> <properties.gen_path> <output_dir>")
        print("   or: gen_props.py --list <properties.gen_path>")
        sys.exit(1)

    if sys.argv[1] == "--list":
        if len(sys.argv) < 3:
            print("Missing properties.gen path")
            sys.exit(1)
        for name in get_prop_names(sys.argv[2]):
            print(name)
        return

    if len(sys.argv) < 4:
        print("Usage: gen_props.py <gen_parser_path> <properties.gen_path> <output_dir>")
        sys.exit(1)

    gen_parser = sys.argv[1]
    properties_gen = sys.argv[2]
    output_dir = sys.argv[3]

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    with open(properties_gen, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if ':' not in line:
                continue
            prop_name = line.split(':')[0].strip()
            output_file = os.path.join(output_dir, f"autogenerated_{prop_name}.c")
            # print(f"Generating {output_file}")
            subprocess.run([gen_parser, "-o", output_file, line], check=True)

if __name__ == "__main__":
    main()
